name: Build Android APK (Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build APK in Buildozer Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer:latest
        options: -v ${{ github.workspace }}:/home/user/hostcwd -w /home/user/hostcwd
        run: |
          yes | buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v7
      with:
        name: audio-anomaly-apk
        path: bin/*.apk






